<template>
  <v-app>
    <v-content>
      <v-container
        fluid
        overflow-hidden
        class="pa-0"
      >
        <router-view/>
      </v-container>
    </v-content>
  </v-app>
</template>
